# Generated by Django 2.0.2 on 2018-10-12 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iconnect', '0003_auto_20181012_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='conversation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='iconnect.Conversation'),
            preserve_default=False,
        ),
    ]
