# Generated by Django 2.0.2 on 2018-10-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iconnect', '0004_comment_conversation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
