# Generated by Django 2.0.2 on 2018-10-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iconnect', '0007_auto_20181014_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default=False, upload_to='avatars/'),
            preserve_default=False,
        ),
    ]
