# Generated by Django 2.0.2 on 2018-10-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iconnect', '0008_auto_20181015_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
