# Generated by Django 2.0.2 on 2018-10-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iconnect', '0010_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_invalid',
            field=models.BooleanField(default=False),
        ),
    ]
