# Generated by Django 2.0.2 on 2018-11-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iconnect', '0013_comment_is_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
